### ISSUE TITLE
Pixelation when filling with RGBA source after stroking with RGB/RGBA source

### ISSUE THREAD

**Issue by PMende** [SimonSapin/cairocffi#53]
The issue as described in the title occurs whether you stroke first or fill first, so long as the second operation is done with an RGBA source with A<1.

Test script to reproduce the effect:

import cairocffi as cairo

w, h = 237.6, 237.6
test_surf = cairo.PSSurface('test.ps', w, h)

a = cairo.Context(test_surf)
a.translate(w/2,h/2)
a.rotate(pi/4)
r_w, r_h = 175, 100
a.rectangle(-r_w/2,-r_h/2,r_w,r_h)
a.set_source_rgba(0,0,1,0.75)
a.fill_preserve()
a.set_source_rgba(1,0,0,0.25)
a.set_line_width(6)
a.stroke_preserve()

Is anyone else able to reproduce this? I'm not sure if it's an issue with GSView (i.e., that it's not a real effect - I'm doubtful of this), an issue with Cairo, or whether I'm doing something incorrectly with Cairo (I'm fairly new to it). I would upload a PNG showing what I mean, but the issue will be clearer, I think, if one were to simply to run the test script and examine the resulting PS file.

**Comment by SimonSapin** [comment]
What do you mean by pixelation? What is the issue? Is this issue at all related to the cairocffi bindings, rather than [cairo](http://cairographics.org/) itself? (i.e., can you reproduce the issue with pycairo?)

Wild guess: do you mean that the PostScript file contains a raster image rather than vectors? This is because [the PostScript file format does not support partial transparency](http://en.wikipedia.org/wiki/Transparency_%28graphic%29#Transparency_in_PostScript) (the best it can do it 1-bit alpha channels), so cairo falls back to rendering a raster image and embedding that in the file.

Not only is this unrelated to cairocffi (and so doesn’t have its place in this issue tracker), but it’s not something that cairo can fix either since it’s a limitation of the file format you’re using. There are two things you can do:

* Increase the resolution of the fallback image: http://pythonhosted.org/cairocffi/api.html#cairocffi.Surface.set_fallback_resolution
* Use a better file format. Both PDF and SVG (also supported by cairo) do better here.

**Comment by PMende** [comment]
Ah. I didn't realize PS didn't have support for this. Sorry for the inconvenience, and thanks for your quick response!
