### ISSUE TITLE
TypeError: must be cairo.Matrix, not Matrix

### ISSUE THREAD

**Issue by ykmm** [SimonSapin/cairocffi#70]
Hi, I am new to cairo, so maybe this is just a usage problem, however I was not able to find anything online about similar issues.

I get a TypeError: must be cairo.Matrix, not Matrix when trying to use matrices with cairocffi

the error disappears by switching the import to:
> import cairo

    #!/usr/bin/env python
    
    import sys
    import cairocffi as cairo
    import rsvg
    import gtk
    
    
    BORDER_WIDTH = 10
    
    
    def delete_cb(win, event):
        gtk.main_quit()
    
    
    def expose_cairo(win, event, svg):
    
        x, y, w, h = win.allocation
        cr = win.window.cairo_create()
        cr.set_source_color(win.style.fg[win.state])
        cr.rectangle(BORDER_WIDTH, BORDER_WIDTH,
                    w - 2*BORDER_WIDTH, h - 2*BORDER_WIDTH)
        cr.set_line_width(5.0)
        cr.set_line_join(cairo.LINE_JOIN_ROUND)
        cr.stroke()
    
        if svg != None:
            matrix = cairo.Matrix(3,0,0,3,0, 0)
            #cairo.Matrix.rotate( matrix, prop.rot )
            cr.transform (matrix)
            svg.render_cairo(cr)
    
        return True
    
    def main():
        win = gtk.Window ()
        win.connect("delete-event", delete_cb)
    
        svg = None
        if (len (sys.argv) > 1):
            svg = rsvg.Handle(file=sys.argv[1])
        elif True:
            svg = rsvg.Handle(file='somefile.svg')
        else:
            raise SystemExit("need svg file")
    
        win.connect("expose-event", expose_cairo, svg)
    
        print svg.props.width, svg.props.height, svg.props.em, svg.props.ex
    
        win.show_all()
        win.connect("destroy", lambda w: gtk.main_quit())
        gtk.main()
    
    if __name__ == '__main__':
        main()

**Comment by SimonSapin** [comment]
I’m gonna close this as it is not a cairocffi bug, but here is what’s going on:

There are a number of different projects involved here, each with different maintainers (or lacking maintainers…):

* cairo, GTK+, and rvg are C libraries. They’re respectively for 2D graphics, a UI toolkit, and for rendering SVG.
* pycairo, PyGTK and pyrsvg are Python bindings for cairo, GTK+, and rsvg, all written in C against the CPython extension API . They’re what you get with `import cairo`, `import gtk`, and `import rsvg`.
* cairocffi (this project) is a set of Python bindings for cairo written in Python using CFFI. It’s an alternative to pycairo.
* [CFFI](https://cffi.readthedocs.org/en/latest/) is a Python library for calling into C libraries. It’s much easier to use than the CPython extension API.

GTK+ and rvg both integrate with cairo: the former can provide you an cairo "context" to draw to, and the latter can draw to a such cairo context.

PyGTK and pyrsvg expose this by integrating with pycairo. One has APIs that return a `cairo.Context` object, and the other has APIs that take a `cairo.Context` object as a parameter. `cairo` here means pycairo.

The `TypeError` you’re getting here is because the `transform` method of pycairo’s `Context` object expect a `Matrix` object from pycairo, not from cairocffi.

I know of four possible ways forward for you:

* If you want to avoid pycairo completely and only use cairocffi, you need to avoid PyGTK, PyGObject, and pyrsvg as well. Instead, you can call into GTK+ or rsvg directly with CFFI, [like I do in WeasyPrint](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/text.py). This is viable if only call a small number of C APIs.
* Try [pgi](https://github.com/lazka/pgi) as an alternative to PyGTK/pyrsvg. It can integrate with cairocffi, but it says “Development Status: WARNING: Lots of things are not implemented/supported.”
* If you’re stuck with using pycairo anyway, do you need cairocffi at all? Maybe using only pycairo would work for you.
* If for some reason you want both in the same project, https://pythonhosted.org/cairocffi/cffi_api.html#converting-pycairo-wrappers-to-cairocffi has some dirty hacks to convert between a pycairo context and a cairocffi context.

For some context:

pycairo is abandoned, with its last release in 2011. I submitted some patches to it a couple years ago and never got a response. It does not expose some of cairo’s more recent features. It’s also hard to install in a virtualenv. This is why I made cairocffi.

pygtk is abandoned, with its last release also in 2011. The GTK+ maintainers recommend using the introspection-based PyGObject instead. PyGObject also integrates with pycairo, so it wouldn’t solve your issue.

(I don’t know the status of rsvg or pyrsvg, other than [CairoSVG](https://github.com/Kozea/CairoSVG ) (yet another project) is an alternative.)

**Comment by ykmm** [comment]
Hi Simon, thanks for taking the time to write such a long answer, my main goal is to use cairo from python (using cairocffi) and having the possibility to draw in a windowing system (I used gtk because it was in a lot of examples, but I have no issues using wxpython or tkinter instead, would you have a suggestion?). 

There is one thing I don't understand from your explanation, you say that I am using pycairo,  unless it is the library used by pygtk to execute this code `cr = win.window.cairo_create()`. Incidentally I think that's the reason why `cr.transform (matrix)` gives the Typeerror (it is expecting a cairocffi matrix instead it got a pycairo one).

thanks again (I hope the bug did not get open again, in case I will not comment anymore)

**Comment by SimonSapin** [comment]
> you say that I am using pycairo, unless it is the library used by pygtk to execute this code `cr = win.window.cairo_create()`.

Yes, exactly. The `cr` object returned by PyGTK here is a pycairo context object, not a cairocffi context object.

> Incidentally I think that's the reason why cr.transform (matrix) gives the Typeerror (it is expecting a cairocffi matrix instead it got a pycairo one).

The other way around.

(Commenting is fine. It does not re-open bugs automatically.)

**Comment by ykmm** [comment]
For the record (if anyone has the same issue), I managed to have it working by converting the pycairo context to a cairocffi context by using `_UNSAFE_pycairo_context_to_cairocffi` on the context returned by `cr = win.window.cairo_create()`, I had also to use `_UNSAFE_cairocffi_context_to_pycairo` to convert the cairocffi context to a pycairo one in order to have rsvg working correctly (both functions from https://pythonhosted.org/cairocffi/cffi_api.html#converting-pycairo-wrappers-to-cairocffi).

**Comment by SimonSapin** [comment]
The second conversion might not be necessary, both wrappers affect the same reference-counted C-level object under the hood.
